version: 2

models:
  - name: stg_weather
    columns:
      - name: city
        tests: [not_null]
      - name: ts
        tests: [not_null]
      - name: temperature_c
        tests: [not_null]

  - name: stg_air_quality
    columns:
      - name: city
        tests: [not_null]
      - name: ts
        tests: [not_null]
